[package]
name = "monado-sys"
version = "0.0.1"
edition = "2021"
rust-version = "1.70"
authors = ["alvr-org", "Monado", "Meister1593"]
license = "MIT OR BSL-1.0"

[build-dependencies]
cmake = "0.1"
bindgen = "0.69"
walkdir = "2"
